### ISSUE TITLE
MBcache

### ISSUE THREAD

**Issue by Pyrosfr** [Mar2zz/LaSi#1]
Hello,

Just install your script and got some strange issue :

I juste add a "whoami" in the original script to verify :
#### PROCESSING FILES

process () {
echo "--------------------------"
echo $(date)
echo "Starting renamealbum for $NZB"
whoami
/usr/bin/python /usr/bin/renamealbum -R --no-embed-coverart "$DIR"

echo $(date)
echo "Album search ended for $NZB"
}
# As you can see, it display my real login name, but try to use the root .mbcache.

The sabnzbd process run with my own account.
the /etc/passwd is correct and the ~ links to the /home/pyrosfr folder

I can't understand this issue

thx
# report.txt

Starting renamealbum for XXXXXXXXXXXX
# pyrosfr

----renamealbum started----
Using naming scheme: %(sortalbumartist)s - %(year)i - %(album)s/%(tracknumber)02i - %(trackartist)s - %(trackname)s
Source path: /media/music/XXXXXXXXXXXX
]0;Renaming /media/music/XXXXXXXXXXXX\Skipping calculating discID
Traceback (most recent call last):
File "/usr/bin/renamealbum", line 362, in process_one_path
    renamealbum(srcpath, options)
File "/usr/bin/renamealbum", line 698, in renamealbum
    (release, method) = get_musicbrainz_release (disc, options)
File "/usr/bin/renamealbum", line 223, in get_musicbrainz_release
    memocache.remove_from_cache("delayed_get_releases_by_discid", disc.discid)
File "/usr/lib64/python2.7/site-packages/renamealbum/memocache.py", line 82, in remove_from_cache
    _assure_memocache_open(funcname)
File "/usr/lib64/python2.7/site-packages/renamealbum/memocache.py", line 54, in _assure_memocache_open
    os.mkdir(os.path.expanduser("~/.mbcache/"))
OSError: [Errno 13] Permission denied: '/root/.mbcache/'
fail!

**Comment by Mar2zz** [comment]
Can you confirm if this problem still exists after git pulling the latest album identify and using this script?
http://dl.dropbox.com/u/18712538/AlbumIdentify/SabtoAlbum.sh <- please edit variables before using it.

**Comment by Mar2zz** [comment]
Solution is here:
https://github.com/scottr/albumidentify/issues/76
