### ISSUE TITLE
Couldn't find package python-pip

### ISSUE THREAD

**Issue by skabaas** [Mar2zz/LaSi#10]
Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package python-pip

Installing Subliminal on a ReadyNAS NV+. How can I fix this?

**Comment by Mar2zz** [comment]
Does it have apt? apt-cache search pip or try sudo apt-get easy_install (which has almost te same functions). the script you are using is written for ubuntu/debian, what os is it running?

**Comment by Mar2zz** [comment]
If you do apt-cache search pip I could solve this perhaps. Did you try?

**Comment by skabaas** [comment]
Yeah, I tried, but my ReadyNas can't find pip. Installed subliminal using "easy_install subliminal", which worked like a charm!

**Comment by Mar2zz** [comment]
Ok thx. Easy-install also works on ubuntu/debian systems, so I will make a fallback for it if 'Couldn't find package python-pip' error occurs.

**Comment by Mar2zz** [comment]
ok gefixed denk ik..
denk dat je pip niet systemwide staat, aangezien je wel de pip-check bent doorgekomen met het script, dus heb 2 oplossingen gemaakt en net gepushed.
