### ISSUE TITLE
installatie CouchPotato

### ISSUE THREAD

**Issue by zeuslooye** [Mar2zz/LaSi#11]
Hoi

mooie scripts, ik krijg de volgende fout melding. kan jij helpen

ps ik gebruik een synology

2011-11-13 17:39:34 (36.0 KB/s) - `/opt/etc/init.d/S99couchpotato.sh' saved [4327/4327]

/opt/etc/init.d/S99couchpotato.sh: line 76: syntax error: unexpected "}"

Failed! Installing CouchPotato didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

**Comment by Mar2zz** [comment]
Gefixed. Bedankt voor het melden. Als je de install opnieuw uitvoert dan zou dit opgelost moeten zijn.
