### ISSUE TITLE
installatie stickbeard & headphones

### ISSUE THREAD

**Issue by zeuslooye** [Mar2zz/LaSi#12]
hallo

bij de installatie van stickbeard krijg ik de volgende fout melding. en de applicatie draait achteraf niet. 

ps ik gebruik een synology

2011-11-13 17:49:50 (35.5 KB/s) - `/opt/etc/init.d/S99sickbeard.sh' saved [4336/4336]

grep: /volume1/@appstore/sickbeard/config.ini: No such file or directory
grep: /volume1/@appstore/sickbeard/config.ini: No such file or directory
grep: /volume1/@appstore/sickbeard/config.ini: No such file or directory
grep: /volume1/@appstore/sickbeard/config.ini: No such file or directory
- SickBeard daemon already running

Done! Installed SickBeard.
SickBeard is by default located @ http://synology_ip:8081

net installeer ik headphones en ik krijg de zelfde fout 

2011-11-13 17:52:57 (36.3 KB/s) - `/opt/etc/init.d/S99headphones.sh' saved [4269/4269]

grep: /volume1/@appstore/headphones/config.ini: No such file or directory
grep: /volume1/@appstore/headphones/config.ini: No such file or directory
grep: /volume1/@appstore/headphones/config.ini: No such file or directory
grep: /volume1/@appstore/headphones/config.ini: No such file or directory
- Headphones daemon already running

Done! Installed Headphones.
Headphones is by default located @ http://synology_ip:8181

**Comment by Mar2zz** [comment]
Ik ga eerst ff voetballen, maar dit is makkelijk te fixen. in het initscript staat $APP_PATH ipv $CFG_PATH bij hostcheck. 
Zal vanavond even nieuwe files in de dropbox zetten. bedankt voor het melden. Expect fixes around 22:00

**Comment by Mar2zz** [comment]
Als het goed is allemaal gefixed. Waren erg slordige foutjes van mijn kant... :)

**Comment by zeuslooye** [comment]
Bedankt voor de aanpassing script lijkt nu te werken maar de
applicatie nog niet. Morgen ga ik weer verder proberen. Tnx en ga zo
door de scripts zijn een goed idee

Op 13 nov. 2011 om 19:28 heeft Mar2zz
reply@reply.github.com
het volgende geschreven:

**Comment by Mar2zz** [comment]
Iets aangepast waardoor ie nu zou moeten starten. zou je willen proberen en willen melden als het nu werkt?

**Comment by zeuslooye** [comment]
stick beard is nu goed gegaan.
CouchPotato is zonder fouten geïnstalleerd maar hij doet het nog niet.
de ander gaven ook nog een paar fouten. ik reboot mijn syno even om te kijken of dat het dan beter gaat

alvast erg bedankt voor het helpen

Op 14 nov. 2011, om 06:22 heeft Mar2zz het volgende geschreven:

**Comment by Mar2zz** [comment]
En, wat is de uitslag?

**Comment by zeuslooye** [comment]
Krijg ipkg niet meer aan de praat. Hoop dat ik het weekend meer rijder
voor heb.

Op 18 nov. 2011 om 09:16 heeft Mar2zz
reply@reply.github.com
het volgende geschreven:

**Comment by zeuslooye** [comment]
ik krijg nu de volgende fouten

Saving a basic .beetsconfig-sample in /volume1/@appstore/.beets, edit it and copy it to the home-folders ...
Command: cp -f /volume1/@appstore/.beets/.beetsconfig-sample /home/''user-running-beets''/.beetsconfig
--2011-11-20 20:53:37--  http://dl.dropbox.com/u/18712538/Synology/beets/.beetsconfig-sample
Resolving dl.dropbox.com... 107.20.206.187, 107.20.230.29, 107.22.172.16, ...
Connecting to dl.dropbox.com|107.20.206.187|:80... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2011-11-20 20:53:38 ERROR 404: NOT FOUND.

Failed! Installing Beets didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

---

2011-11-20 20:56:26 (32.4 KB/s) - `/opt/etc/init.d/S99couchpotato.sh' saved [4474/4474]

sh: missing ]
First run, creating config.ini
- Starting CouchPotato ...
  chown: unknown user/group couchpotato:users
  su: unknown user couchpotato
  Fail!
  Done!

Done! Installed CouchPotato.
CouchPotato is by default located @ http://synology_ip:5050

---

2011-11-20 21:12:25 (38.2 KB/s) - `/opt/etc/init.d/S99couchpotato.sh' saved [4474/4474]

sh: missing ]
First run, creating config.ini
- Starting CouchPotato ...
  chown: unknown user/group couchpotato:users
  su: unknown user couchpotato
  Fail!
  Done!

Done! Installed CouchPotato.

## CouchPotato is by default located @ http://synology_ip:5050

fatal: destination path 'headphones' already exists and is not an empty directory.

Failed! Installing Headphones didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

---

100%[=========================================================================================================================================================================>] 4,479       --.-K/s   in 0.1s    

2011-11-20 21:14:13 (38.3 KB/s) - `/opt/etc/init.d/S99sickbeard.sh' saved [4479/4479]

sh: missing ]
First run, creating config.ini
- Starting SickBeard ...
  Done!

Done! Installed SickBeard.

## SickBeard is by default located @ http://synology_ip:8081

kan jij hier iets mee

jeroen

Op 18 nov. 2011, om 12:56 heeft Jeroen I. Looye het volgende geschreven:

**Comment by Mar2zz** [comment]
beets fout gefixed. ik had het bestand zonder . ervoor in dropbox staan daarom kon ie ḿ niet vinden. 
Je kunt 't bestand nu ook eventueel handmatig downloaden:
http://dl.dropbox.com/u/18712538/Synology/beets/beetsconfig-sample

**Comment by zeuslooye** [comment]
lijkt nu goed te gaan met beets

Using /opt/local/lib/python2.6/site-packages/pip-1.0.2-py2.6.egg
Processing dependencies for pip
Finished processing dependencies for pip
Requirement already satisfied (use --upgrade to upgrade): beets in /opt/local/lib/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): mutagen in /opt/local/lib/python2.6/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): python-musicbrainz2>=0.7.2 in /opt/local/lib/python2.6/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): munkres in /opt/local/lib/python2.6/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): unidecode in /opt/local/lib/python2.6/site-packages (from beets)
Cleaning up...

```
Done! Installed Beets.
Type /opt/local/bin/beet --help for options or
start importing music with /opt/local/bin/beet import /path/to/music.
```

tnx so far

Op 21 nov. 2011, om 21:07 heeft Mar2zz het volgende geschreven:

**Comment by Mar2zz** [comment]
Brickman heeft wat code hier gewijzigd voor de synology sickbeard/couchpotato/headphones-installers, 't zou nu wel eens kunnen werken.

**Comment by Mar2zz** [comment]
volgens mij geen issue meer

**Comment by zeuslooye** [comment]
Sorry voor de late reactie. Maar inderdaad is opgelost

Op 24 jan. 2012 om 07:20 heeft Mar2zz
reply@reply.github.com
het volgende geschreven:
