### ISSUE TITLE
Diverse problemen bij de installatie van Spotweb

### ISSUE THREAD

**Issue by ghost** [Mar2zz/LaSi#13]
Diverse problemen bij de installatie van Spotweb via de Synology installer.

1.
Het lijkt erop dat de Spotweb file ownsettings.php is hernoemd naar settings.php.

2.
Directory /volume1/@appstore/.spotweb wordt niet aangemaakt.

3.
Spotweb wordt alleen gecloned als er geen eerdere installatie aanwezig is.
Anders wordt alleen de directory verwijderd.

4.
Linken van de settings.php file gaat niet goed.

5.
Zetten van een MySQL password wordt niet uitgevoerd althans zo lijkt het.

6.
File /volume1/@appstore/.spotweb/settings.php kan niet worden geinclude in de upgrade.php.
Dit i.v.m. open_basedir restrictie.

**Comment by Mar2zz** [comment]
Thx! lots of info, daar kan ik wat mee :)
1. dat kan ik niet vinden? ik gebruik het woord settings nergens. 
2. klopt, gefixed, mogelijk ook oplossing voor issue 1.
3. klopt, gefixed.
4. klopt, zie 1 en 2. (symlink /volume1/@appstore/.spotweb/ownsettings.php naar /volume1/web/spotweb/ownsettings.php)
5. het intypen van het wachtwoord is onzichtbaar gemaakt, bewust, maar kan zijn dat ash van syno daar niet goed mee omgaat? kreeg je mysql foutmeldingen? zo ja, welke?
6. Ik snap niet wat daar staat. Kan je misschien een oplossing aandragen? moet ik 'm ergens anders neergooien? 
fixes staan online, als je het script opnieuw uitvoert zou je een stuk verder moeten komen.

**Comment by ghost** [comment]
1.
Spotweb zelf noemt deze file nu settings.php.
5.
Ik dacht eigenlijk dat het nieuwe password ook gezet zo worden op mysql voor gebruiker root maar misschien heb ik dit verkeerd begrepen.
6.
Op de syno in php mag je standaard niet aan files refereren die buiten je web directory staan.
De dir @appstore moet je dan toevoegen in usersettings file.
Ik zal precieze dit later doorgeven ik tik nu op mijn mobiel.

**Comment by ghost** [comment]
Oh ja, de inhoud van de Spotweb settings file is ook gewijzigd zo wordt er nu ook het DB type aangegeven.
Jouw file in de dropbox is niet meer actueel dacht ik.

**Comment by Mar2zz** [comment]
Als het goed is die dropbox-ownsettings wel actueel. De database die het installscript aanmaakt komt exact overeen met de default settings zoals in settings.php staan. En hoeven ze dus niet nogmaals in ownsettings.php te staan. 

Mysql password: Het installscript vraagt om het wachtwoord voor de mysql-server en user root zodat het acties kan ondernemen mbt aanmaken database. Dit wachtwoord heeft verder niets te maken met het wachtwoord op de spotweb-database, wat by default gewoon 'spotweb' is. 

Wat betreft de settings.php en ownsettings.php; Het is best practice om alleen die zaken die je anders wilt hebben ten opzichte van de beschreven opties in settings.php in een ownsettings.php te zetten en daar aan te passen. De settings.php kun je beter niet aanzitten, dat geeft problemen met updaten van gitsource.

De php van syno zou volgens mij niet het verschil moeten kunnen ontdekken tussen een symlink naar een file en een normale file. In de webdirectory word een symlink naar de ownsettingsfile gezet die buiten die directory staat en php zou moeten vinden dat ie lokaal staat dan. Maar ik kan het mis hebben, synology verrast me wel vaker met afwijkingen die niet 'normaal' zijn in linux-country vanwege de uitgeklede busybox.

**Comment by ghost** [comment]
Ach, nu snap ik m van de ownsettings file.
Mysql duidelijk. Verkeerd begrepen.
Die open base dir melding ga ik nog eens nakijken.
Ik ga testen zodra eik de kans krijg.
Bedankt zover!

**Comment by Jeroenve** [comment]
Door "/volume1/@appstore" toe te voegen aan de open_basedir is de .spotweb folder toegestaan.

Door veranderen bevat ownsetting atm alleen de mysql settings!

**Comment by Mar2zz** [comment]
Jeroen hoe voeg ik dat toe vanuit een scripted install? ik heb geen syno dus weet bestandslocaties niet en de effecten van sed niet altijd.

**Comment by Jeroenve** [comment]
> We now set "open_basedir" in /usr/syno/etc/php/user-setting.ini
> Open_basedir staat in /usr/syno/etc/php/user-setting.ini.

/usr/syno/etc/php/user-setting.ini:
`open_basedir = /etc.defaults:/usr/bin/php:/usr/syno/synoman:/etc:/var/run:/tmp:/var/spool/php:/volume1/@tmp/php:/var/services/web:/var/services/photo:/var/services/blog:/var/services/homes`

**Comment by Mar2zz** [comment]
Ik het het toch maar even anders gedaan. Vind het niet prettig om in systemfiles te inserten, straks gaat er iets stuk ofzo. Dus ownsettings gewoon weer naar de spotwebfolder gezet, maar met een backupje in .spotweb. Het script checkt tijdens install of die daar staat en pakt 'm dan op.

**Comment by Mar2zz** [comment]
speelt dit issue nog? of andere met spotweb?

**Comment by ghost** [comment]
Ik heb uiteindelijk handmatig geinstalleerd en daarna het script niet meer hoeven gebruiken.
