### ISSUE TITLE
Foutje in de subliminal scripts

### ISSUE THREAD

**Issue by Jeroenve** [Mar2zz/LaSi#17]
De check of de tweede taal aanwezig werkte niet op de synology. Verder de optie toegevoegd om PLUGINS leeg te laten en zodoende alle plugins te gebruiken.

``` shell
PLUGINS='BierDopje'                                 # Set your plugins or leave empty to use all
                                                    # Available, but may not work: PLUGINS = BierDopje OpenSubtitles SubsWiki Subtitulos TheSubDB
                                                    # example for several plugins: PLUGINS='BierDopje Subtitulos'

# set lang 1 and/or lang 2
[ -n "$lang1" ] && LANGS="-l $lang1"
[ -n "$lang2" ] && LANGS="$LANGS -l $lang2 -m"

# Check is a plugin is selected, otherwise use all
[ -n "$PLUGINS" ] && PLUGINS="-p $PLUGINS"
```

**Comment by Mar2zz** [comment]
Hmm die files heb ik nog niet in git zitten. Waar komt ie vandaan? ik dacht ik pas 't even aan maar welke file gaat het over :p

**Comment by Jeroenve** [comment]
In subliminal.sh

**Comment by Mar2zz** [comment]
Ok. Ik zal al mijn postprocessing-scripts ook wel even in github zetten.

**Comment by Jeroenve** [comment]
Ik heb de temp files ook aangepast naar `/volume1/@tmp/` zodat de harddisk uit hibernation wordt gehaald als de cronjob wordt gedraaid.

`TMP_FILE="/volume1/@tmp/.subliminal";   # Tmp file variable`
