### ISSUE TITLE
Verwijder programma

### ISSUE THREAD

**Issue by ghost** [Mar2zz/LaSi#18]
Goede avond, 
Ik probeer Beets te verwijderen en volgens je Readme kan dat via apt-get remove (purge) maar daar staat Beet(s) niet bij.
De reden waarom ik het wil verwijderen is omdat er op 1 of andere reden geen één plugin is mee gekomen met de installatie en heb dus een helemaal leeg .beets mapje in me user directory.
Ik heb Beets kunnen verwijderen door pip uninstall te doen, maar dit is niet ideaal.

Verder wou ik even melden dat je fantastisch werk doet! 
Gegroet!

**Comment by Mar2zz** [comment]
sudo pip uninstall beets en beets wordt gedeinstalleerd. Ik zal de readme updaten daarmee.
