### ISSUE TITLE
kan iemand mij helpen aan een ownsettings.php

### ISSUE THREAD

**Issue by zeuslooye** [Mar2zz/LaSi#19]
Kan iemand mij helpden aan ownsettings.pho met alle instellingen er in die ik kan installen.

Ik heb wat problemen met het lokaal opslaan op mijn syno.

ik vind in mijn ownsettings geen info over nzbhandling.

tnx

**Comment by Mar2zz** [comment]
Met de huidige versie van spotweb sla je alles op in de database. Een ownsettings.php is niet meer nodig.
