### ISSUE TITLE
installing spotweb

### ISSUE THREAD

**Issue by aegis123** [Mar2zz/LaSi#23]
Hi mar2zz,

is it possible to make installing apache/mysql/php5 optional when you want to install spotweb.
i already have a webserver installed but still apache gets installed. also maybe making an option about asking where to install spotweb would be nice to? my for instance my webroot is not located in /var/www but somewhere else but spotweb still gets installed to the /var/www dir.

btw great job on the script makes installing everything nice and easy :)

**Comment by Mar2zz** [comment]
Sure, can do. You have to patient though, all my focus is on 
LazyLibrarian now. Will write it in a week or so. If you know bash you 
could give it a try?
Hint: if ! which apache > /dev/null; then
             #raise question Do you want to install apache/mysql too?
         else
             # install with defaults
         fi

Op 03-02-12 15:44, dylan drost schreef:

**Comment by Mar2zz** [comment]
Ik heb een apache-check gemaakt die afgaat als apache nog niet geinstalleerd is. Alleen omdat ik alles via een .deb file deed worden nu alle andere dependencys ook niet geinstalled. 

Welke dep's heb je wel nodig ook al draai je geen apache?

De fix staat hier. zou je 'm willen testen als je pulled heb je 'm binnen. https://github.com/Mar2zz/LaSi/commit/83a413b496a219552a4f5547694e306bd0e81db5
