### ISSUE TITLE
error installing maraschino

### ISSUE THREAD

**Issue by aegis123** [Mar2zz/LaSi#26]
I'm getting this error when installing maraschino.
I ran it twice. deleting the folder /opt/maraschino after the first run.

Setting up maraschino (2012.01.04) ...
fatal: destination path '/opt/maraschino' already exists and is not an empty directory.
dpkg: error processing maraschino (--configure):
 subprocess installed post-installation script returned error exit status 128
Errors were encountered while processing:
 maraschino
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Mar2zz** [comment]
Don't delete by hand. Apt is used for install, so sudo apt-get purge maraschino and then reinstall should fix this I hope. (btw fixed the /tmp/./LaSi.sh thingy. thx for reporting.
