### ISSUE TITLE
http://....../spotweb/?page=editsettings opent niet

### ISSUE THREAD

**Issue by kajrietberg** [Mar2zz/LaSi#27]
Hoi,

Ik heb Ubuntu, maar ben niet zeer bekent met programmeren. Wilde jou script proberen. Het loopt erg mooi totdat ik de nieuwsservertab iets mee moet doen. De link die aangegeven wordt in de titel opent niet in een webbrowser. Ik kan de bestanden wel met een editor openen, maar dan zie ik niet waar ik wat moet veranderen. Wat kan ik nu doen?

**Comment by Mar2zz** [comment]
De apacheserver moet herstart worden anders worden de php bestanden als textbestanden geserveerd ipv readable by browser, pc herstarten heeft zelfde effect. Ik heb het in het script in ieder geval nog even extra gedaan aan het einde dus nu moet dat goed gaan.
