### ISSUE TITLE
Issues installing on CrunchBang

### ISSUE THREAD

**Issue by PadraicODonoghue** [Mar2zz/LaSi#29]
I've been trying to use your installer on crunchbang (Debian based distro). I've tried this on a Laptop running #! and in VirtualBox with the same results
This log is from the VB clean install
2012-03-04 21:42:09 URL:http://dl.dropbox.com/u/18712538//LaSi_Repo/couchpotato.deb [4584/4584] -> "/tmp/couchpotato.deb" [1]
Selecting previously deselected package couchpotato.
(Reading database ... 85721 files and directories currently installed.)
Unpacking couchpotato (from /tmp/couchpotato.deb) ...
Setting up couchpotato (2011.12.30) ...
Cloning into /opt/couchpotato...
remote: Counting objects: 9164, done.
remote: Compressing objects: 100% (3073/3073), done.
remote: Total 9164 (delta 6221), reused 8899 (delta 5977)
Receiving objects: 100% (9164/9164), 4.50 MiB | 119 KiB/s, done.
Resolving deltas: 100% (6221/6221), done.
dpkg: error processing couchpotato (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 couchpotato

Solving dependencys...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up couchpotato (2011.12.30) ...
fatal: destination path '/opt/couchpotato' already exists and is not an empty directory.
dpkg: error processing couchpotato (--configure):
 subprocess installed post-installation script returned error exit status 128
configured to not write apport reports
                                      Errors were encountered while processing:
 couchpotato
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kierr** [comment]
Same thing for me.

**Comment by Mar2zz** [comment]
Did you install for a second time? The directory /opt/couchpotato should be left alone, LaSi uses apt, so when you want to remove it manual you can do a sudo apt-get remove/purge programname. 

Purging and reinstalling will solve this.
