### ISSUE TITLE
Foutmelding bij installatie SpotWeb

### ISSUE THREAD

**Issue by GJurriens** [Mar2zz/LaSi#3]
Als ik via LaSi.sh Spotweb wil gaan installeren krijg ik de volgende foutmelding:
./LaSi/spotwebinstall.sh: line 651: syntax error near unexpected token '}'
./LaSi/spotwebinstall.sh: line 651: '    }'

Dit is dus net na het downloaden van de file spotwebinstall.sh.

**Comment by GJurriens** [comment]
Ik zie net dat de bron op Github wel klopt op die regel.
De && moet verwijderd worden aan het einde van de regel.

**Comment by GJurriens** [comment]
Misschien dat je de file uit jou dropbox kunt bijwerken zodat anderen niet ook tegen dit probleem aan lopen.

**Comment by Mar2zz** [comment]
tijdje geleden al gedaan neem ik aan, had dit issue nooit gezien :p ik zal het toentertijd wel gefixed hebben :0
