### ISSUE TITLE
LaSi on Freebsd

### ISSUE THREAD

**Issue by ghost** [Mar2zz/LaSi#31]
I am running FreeBSD 9.0-STABLE and I have installed SABnzbd and Sickbeard. Both will start and stop with the init script. But, when installing Couchpotato or Headphones, I get an error when trying to start program using the init script.

headphones already running? (pid=4103).
couchpotato already running? (pid=4103).

ps aux | grep python
_sabnzbd  4104   0.4  0.5 207420  45008  ??  S     7:42PM   0:10.79 python /usr/local/sickbeard/SickBeard.py --qu
_sabnzbd  4103   0.0  0.0  11992   1028  ??  Is    7:42PM   0:00.00 daemon: python[4104](daemon)
_sabnzbd  4164   0.0  0.5 217736  41628  ??  I     7:45PM   0:07.28 /usr/local/bin/python2.7 -OO /usr/local/bin/S
root      4383   0.0  0.0  16232   1140   2  S+    8:02PM   0:00.01 grep python

But, I can start each with:

sudo -u _sabnzbd /usr/sbin/daemon -f -p /usr/local/headphones/headphones.pid python /usr/local/headphones/Headphones.py --quiet
sudo -u _sabnzbd /usr/sbin/daemon -f -p /usr/local/couchpotato/couchpotato.pid python /usr/local/couchpotato/CouchPotato.py --quiet

The init scripts worked on 9.0-RELEASE, but not on 9.0-STABLE. I do not know how to fix.

Thank you

**Comment by SpoBo** [comment]
Struggling with the exact same issue. 9.1 prerelease.

**Comment by ghost** [comment]
Don't know how to fix this, yet. Will have a look.
