### ISSUE TITLE
error installing Maraschino server 

### ISSUE THREAD

**Issue by Burke78** [Mar2zz/LaSi#32]
hi I think i FUBARED something :(

I try to install maraschino but get error

Solving dependencys...
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up maraschino (2012.01.04) ...
fatal: destination path '/opt/maraschino' already exists and is not an empty directory.
dpkg: error processing maraschino (--configure):
 subprocess installed post-installation script returned error exit status 128
No apport report written because MaxReports is reached already
                                                              Errors were encountered while processing:
 maraschino

i checked /opt folder before install there was no maraschino folder

**Comment by Mar2zz** [comment]
fixed. do sudo apt-get purge maraschino and rerun lasi.sh

**Comment by Burke78** [comment]
Thank you :)
