### ISSUE TITLE
LaSi install sabnzbdplus on zfsguru

### ISSUE THREAD

**Issue by apetzel** [Mar2zz/LaSi#33]
===>  Checking if devel/py-cheetah already installed
running easy_install
error: Not a URL, existing file, or requirement spec: '/usr/ports/devel/py-cheetah/work/Cheetah-2.4.4/dist/Cheetah-2.4.4-py2.7-freebsd-8.2-STABLE-amd64.egg'
**\* Error code 1

Stop in /usr/ports/devel/py-cheetah.
**\* Error code 1

Stop in /usr/ports/news/sabnzbdplus.

Failed! Installing Sabnzbd didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

**Comment by ghost** [comment]
This issue is related to SAB, not LaSi. I'm sorry I can't help you with that other then to say: Try again later.
Or you can try to install py-cheetah manually and after that install SAB.

**Comment by apetzel** [comment]
Chris,

thank you for your answer but I am new to freebsd and zfsguru do you have any idea how I can add manually py-cheetah? or how I search for the port?

thx
Andreas

## 

Andreas Petzel
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ghost** [comment]
This is the code:

cd /usr/ports/devel/py-cheetah
make install clean

cd /usr/ports/news/sabnzbdplus
make install clean
