### ISSUE TITLE
install headphones on zfsguru 1.9 also with sickbeard and couchpotato

### ISSUE THREAD

**Issue by apetzel** [Mar2zz/LaSi#34]
ls: /usr/local/headphones: No such file or directory
Cloning into '/usr/local/headphones'...
remote: Counting objects: 4619, done.
remote: Compressing objects: 100% (2007/2007), done.
remote: Total 4619 (delta 2729), reused 4393 (delta 2554)
Receiving objects: 100% (4619/4619), 5.15 MiB | 611 KiB/s, done.
Resolving deltas: 100% (2729/2729), done.
chown: share: Invalid argument
ls: /usr/local/etc/rc.d/headphones: No such file or directory
headphones                                    100% of 2469  B 7259 kBps
Starting headphones.
su: unknown login: share
/usr/local/etc/rc.d/headphones: WARNING: failed to start headphones

Failed! Installing Headphones didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

**Comment by ghost** [comment]
I think you're running FreeBSD 8 system image. If so, the user 'share' doesn't exist. This user was introduced in ZFSguru 0.2 beta.
The first thing LaSi asks; is to select the user to run the installed apps. You need to choose "OTHER" and then enter "nfs".
