### ISSUE TITLE
destination path '/opt/maraschino' already exists

### ISSUE THREAD

**Issue by vichingo** [Mar2zz/LaSi#35]
Q. Quit
1

Are you sure you want to continue and install Maraschino?

Packagelist is up to date
2012-07-05 16:26:54 URL:http://dl.dropbox.com/u/18712538//LaSi_Repo/maraschino.deb [3362/3362] -> "/tmp/maraschino.deb" [1](Reading database ... 220521 files and directories currently installed.)
Preparing to replace maraschino 2012.01.04 (using /tmp/maraschino.deb) ...
Unpacking replacement maraschino ...
Setting up maraschino (2012.01.04) ...
Cloning into /opt/maraschino...
remote: Counting objects: 7798, done.
remote: Compressing objects: 100% (3249/3249), done.
remote: Total 7798 (delta 4685), reused 7526 (delta 4457)
Receiving objects: 100% (7798/7798), 22.09 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (4685/4685), done.
cp: cannot stat `/opt/maraschino/settings_example.py': No such file or directory
dpkg: error processing maraschino (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead ...
Errors were encountered while processing:
 maraschino

Solving dependencys...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up maraschino (2012.01.04) ...
fatal: destination path '/opt/maraschino' already exists and is not an empty directory.
dpkg: error processing maraschino (--configure):
 subprocess installed post-installation script returned error exit status 128
No apport report written because MaxReports is reached already
                                                              Errors were encountered while processing:
 maraschino
E: Sub-process /usr/bin/dpkg returned an error code (1)

Failed! Installing Maraschino didn't finish, try again or:

**Comment by Mar2zz** [comment]
fixed. do sudo apt-get purge maraschino and reinstall with lasi
