### ISSUE TITLE
Issues installing Headphones

### ISSUE THREAD

**Issue by thoughtcoder** [Mar2zz/LaSi#36]
Hi,
Firstly, thanks for the script!
When I try to run to install Headphones on Ubuntu 12.04 x64 Server I receive the following output:

Options:
1. Install Headphones
2. Remove Headphones
3. Set cronjob for Headphones

B. Back to menu
Q. Quit
1

Are you sure you want to continue and install Headphones?

Packagelist is up to date
http://dl.dropbox.com/u/18712538//LaSi_Repo/headphones.deb:
2012-07-17 09:36:21 ERROR 404: NOT FOUND.
Connection to dropbox failed, try again later
root@oblivion:~/Mar2zz-LaSi-5e62001#

**Comment by Mar2zz** [comment]
fixed. my symlinks for couchpotato and headphones.deb in dropbox were broken for unknow reason.
