### ISSUE TITLE
Upgrade to CouchPotatoServer (v2)

### ISSUE THREAD

**Issue by thoughtcoder** [Mar2zz/LaSi#38]
Hi,

Any chance the script could be upgraded from CouchPotato r36 (or equivalent github version) to the newly released and markedly improved CouchPotatoServer (v2)?
Github Repo: https://github.com/RuudBurger/CouchPotatoServer

I believe most parameters passed by LaSi would be able to remain similar or unchanged. :)

**Comment by Mar2zz** [comment]
Done for the Debian based systems. it installs to couchpotatov2 folder so you can use it next to the original couchpotato if you want to.
