### ISSUE TITLE
na installatie geen begin pagina

### ISSUE THREAD

**Issue by supershadow** [Mar2zz/LaSi#4]
als ik na de installatie (is goed door lopen verder geen problemen gehad)
naar de browser ga om te kijken krijg ik de volgende melding:

Er is een fout opgetreden toen de website  probeerde op te halen. De server kan offline zijn wegens onderhoud of kan onjuist zijn geconfigureerd.

maar als ik naar http://mijn/testinstall.php
is alles oke en werk de pagina wel maar index niet

en ik heb geen idee wat er mis is hoop dat jullie me kunnen helpen
server debian 6 ook geprobeerd op ubuntu

vriendelijk groet
shadow

**Comment by supershadow** [comment]
laat maar ben er al achter db was niet goed geupdate

**Comment by Mar2zz** [comment]
Hoi shadow,
heb je het al opgelost? cd /var/www/spotweb && git pull && php 
upgrade-db.php lost heel vaak wel wat op...

excuses voor de late reactie, had deze mailaccount niet toegevoegd aan 
mijn client dus nooit zitten opletten :p
groeten
marcel

Op 01-06-11 23:11, supershadow schreef:

> als ik na de installatie (is goed door lopen verder geen problemen gehad)
> naar de browser ga om te kijken krijg ik de volgende melding:
> 
> Er is een fout opgetreden toen de website http://www.supershadow.eu/ probeerde op te halen. De server kan offline zijn wegens onderhoud of kan onjuist zijn geconfigureerd.
> 
> maar als ik naar http://www.supershadow.eu/testinstall.php
> is alles oke en werk de pagina wel maar index niet
> 
> en ik heb geen idee wat er mis is hoop dat jullie me kunnen helpen
> server debian 6 ook geprobeerd op ubuntu
> 
> vriendelijk groet
> shadow
