### ISSUE TITLE
fetch: http://dl.dropbox.com/u/36835219/LaSi/LaSi_BSD.sh: Not Found 

### ISSUE THREAD

**Issue by kxy1983s** [Mar2zz/LaSi#43]
Seems this file has dissapeared off the dropbox host. An unable to launch the LaSi.sh on my zfsguru box now, ran fine a few days ago. 

Im a CLI noob but this is where im getting stuck, seems I cant access the file on DB from a browser either

[ssh@zfsguru /home/ssh]$ fetch http://dl.dropbox.com/u/18712538/LaSi/LaSi.sh
LaSi.sh                                       100% of 2466  B 6942 kBps
[ssh@zfsguru /home/ssh]$ chmod +x LaSi.sh
[ssh@zfsguru /home/ssh]$ ./LaSi.sh
Now going to SU
You need to run LaSi.sh again
[root@zfsguru /home/ssh]#
[root@zfsguru /home/ssh]# ./LaSi.sh
ls: /tmp/LaSi: No such file or directory
fetch: http://dl.dropbox.com/u/36835219/LaSi/LaSi_BSD.sh: Not Found
Connection to dropbox failed, try again later

**Comment by ghost** [comment]
Oops my bad. I accidentally moved my git repo. Should work now

**Comment by kxy1983s** [comment]
lol, no worries mate, was hanging out for this, as it seems that zfsguru's
base sabnzb service installation fails thanks for fixing it up

**Comment by kxy1983s** [comment]
Still no dice

console output as follows

[root@zfsguru /home/ssh]# fetch
http://dl.dropbox.com/u/18712538/LaSi/LaSi.sh
LaSi.sh                                       100% of 2466  B   10 MBps
[root@zfsguru /home/ssh]# chmod +x LaSi.sh
[root@zfsguru /home/ssh]# ./LaSi.sh
LaSi_BSD.sh                                   100% of   50 kB   44 kBps
: No such file or directory
[root@zfsguru /home/ssh]#
