### ISSUE TITLE
LaSi_BSD.sh                                   100% of   50 kB   49 kBps : No such file or directory 

### ISSUE THREAD

**Issue by kxy1983s** [Mar2zz/LaSi#44]
Something still not quite right with the BSD shell script.

[root@zfsguru /home/ssh]# fetch http://dl.dropbox.com/u/18712538/LaSi/LaSi.sh
LaSi.sh                                       100% of 2466  B  808 kBps
[root@zfsguru /home/ssh]# chmod +x LaSi.sh
[root@zfsguru /home/ssh]#  ./LaSi.sh
LaSi_BSD.sh                                   100% of   50 kB   49 kBps
: No such file or directory

**Comment by ghost** [comment]
messed up the code with Notepad++

**Comment by kxy1983s** [comment]
Sweet, its working now, intalling sabnzb as we speak
