### ISSUE TITLE
Failing to install sickbeard on FreeBSD

### ISSUE THREAD

**Issue by kxy1983s** [Mar2zz/LaSi#45]
Tried several times removing and re attempting install to no avail.
Options:
1. Install SickBeard
2. Remove SickBeard
3. Update SickBeard

B. Back to menu
Q. Quit
1

Are you sure you want to continue and install SickBeard?

ls: /usr/local/sickbeard: No such file or directory
Cloning into '/usr/local/sickbeard'...
remote: Counting objects: 21187, done.
remote: Compressing objects: 100% (7011/7011), done.
remote: Total 21187 (delta 14442), reused 19832 (delta 13247)
Receiving objects: 100% (21187/21187), 7.80 MiB | 722 KiB/s, done.
Resolving deltas: 100% (14442/14442), done.
ls: /usr/local/etc/rc.d/sickbeard: No such file or directory
sickbeard                                     100% of 2646  B 3139 kBps
sudo: unable to execute /usr/local/etc/rc.d/sickbeard: No such file or directory

Failed! Installing SickBeard didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

Press a key to continue

---

Same issue with Couch Potato

Options:
1. Install CouchPotato
2. Remove CouchPotato
3. Update CouchPotato

B. Back to menu
Q. Quit
1

Are you sure you want to continue and install CouchPotato?

ls: /usr/local/couchpotato: No such file or directory
Cloning into '/usr/local/couchpotato'...
remote: Counting objects: 14391, done.
remote: Compressing objects: 100% (5390/5390), done.
remote: Total 14391 (delta 9100), reused 14064 (delta 8874)
Receiving objects: 100% (14391/14391), 6.21 MiB | 626 KiB/s, done.
Resolving deltas: 100% (9100/9100), done.
couchpotato                                   100% of 3076  B 2382 kBps
sudo: unable to execute /usr/local/etc/rc.d/couchpotato: No such file or directory

Failed! Installing CouchPotato didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

Running on ZFSGuru 

Powered by ZFSguru version 0.2.0-beta7
  Running official system image 9.1-003 featuring FreeBSD 9.1-RC1 with ZFS v28.
  Running Root-on-ZFS distribution.

Also, have been unable to get sickbeard and couch potato running using the zfs service installs

Tried removing the sabnzb service from the controll panel completely then start with LaSi install

Are you sure you want to continue and install Sabnzbd?

Lazy admin Scripted installers ----------------- Mar2zz
                    ___           ___
                   /\  \         /__\
                  /::\  \       /:/ _/_       ___
                 /:/:\  \     /:/ /\  \     /__\
  ___     ___   /:/ /::\  \   /:/ /::\  \   /:/**/
 /\  \   /\**\ /:/_/:/:__\ /:/_/:/:__\ /::\  \
 :\  \ /:/  / :\/:/  \/**/ :\/:/ /:/  / \/:\  \**
  :\  /:/  /   ::/**/       ::/ /:/  /     :\/\**\
   :\/:/  /     :\  \        \/_/:/  /       ::/  /
    ::/  /       :__\         /:/  /        /:/  /
     \/**/         \/**/         \/**/         \/**/

FreeBSD Edition------------------------------ Kriss1981

How do you like to install your software?
Use the Ports Collection or the Packages System

If you don't know what I'm talking about, take a look at:
http://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/ports-overview.html

Options:
1. Ports Collection  <= RECOMMENDED
2. Package System    <= Faster installation than Ports

B. Back to menu
Q. Quit
1

Going to update the Ports Tree

Looking up portsnap.FreeBSD.org mirrors... 6 mirrors found.
Fetching snapshot tag from ec2-ap-northeast-1.portsnap.freebsd.org... done.
Fetching snapshot metadata... done.
Updating from Mon Sep 24 12:37:27 UTC 2012 to Mon Sep 24 21:57:22 UTC 2012.
Fetching 4 metadata patches... done.
Applying metadata patches... done.
Fetching 0 metadata files... done.
Fetching 50 patches.....10....20....30....40....50 done.
Applying patches... done.
Fetching 1 new ports or files... done.
Removing old files and directories... done.
Extracting new files:
/usr/ports/MOVED
/usr/ports/Mk/bsd.apache.mk
/usr/ports/UPDATING
/usr/ports/astro/libroadnav/
/usr/ports/astro/osmosis/
/usr/ports/astro/roadnav/
/usr/ports/audio/freeswitch-music/
/usr/ports/audio/freeswitch-sounds/
/usr/ports/converters/osm2pgsql/
/usr/ports/deskutils/steadyflow/
/usr/ports/devel/lpc21isp/
/usr/ports/devel/p5-DateTime-TimeZone/
/usr/ports/devel/p5-SVN-Web/
/usr/ports/devel/p5-Scope-Upper/
/usr/ports/devel/urjtag/
/usr/ports/finance/R-cran-gmm/
/usr/ports/graphics/skanlite/
/usr/ports/graphics/zathura-pdf-poppler/
/usr/ports/lang/seed7/
/usr/ports/mail/opensmtpd/
/usr/ports/multimedia/vlc/
/usr/ports/ports-mgmt/pbi-manager/
/usr/ports/security/quantis-kmod/
/usr/ports/security/quantis/
/usr/ports/sysutils/915resolution/
/usr/ports/sysutils/Makefile
/usr/ports/sysutils/beadm-devel/
/usr/ports/sysutils/libzeitgeist/
/usr/ports/sysutils/password-store/
/usr/ports/textproc/Makefile
/usr/ports/textproc/aspell/
/usr/ports/textproc/en-aspell/
/usr/ports/www/httpcore/
/usr/ports/www/mod_amazon_proxy/
/usr/ports/www/mod_asn/
/usr/ports/www/mod_dnssd/
/usr/ports/www/mod_fcgid/
/usr/ports/www/mod_log_mysql/
/usr/ports/www/mod_pagespeed/
/usr/ports/www/mod_perl2/
/usr/ports/www/mod_spdy/
/usr/ports/www/mod_vhost_ldap/
/usr/ports/www/mod_whatkilledus/
/usr/ports/www/mod_xml2enc/
/usr/ports/www/p5-CGI-SpeedyCGI/
/usr/ports/www/phpbb3/
/usr/ports/www/subsonic/
/usr/ports/x11-clocks/xfce4-timer-plugin/
/usr/ports/x11-fonts/sourcesanspro-ttf/
/usr/ports/x11-themes/gtk-xfce-engine/
/usr/ports/x11-toolkits/girara/
Building new INDEX files... done.
===>  License GPLv2 GPLv3 PSFL CHERRYPY CONFIGOBJ FEEDPARSER GNTP JSON KRONOS LISTQUOTE MSGFMT PYNEWSLEECHER RARFILE RSSLIB SSMTPLIB accepted by the user
=> SABnzbd-0.7.3-src.tar.gz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch http://heanet.dl.sourceforge.net/project/sabnzbdplus/sabnzbdplus/0.7.3/SABnzbd-0.7.3-src.tar.gz
SABnzbd-0.7.3-src.tar.gz                      100% of 2197 kB  127 kBps 00m00s
===>  Extracting for sabnzbdplus-0.7.3
=> SHA256 Checksum OK for SABnzbd-0.7.3-src.tar.gz.
===>  Patching for sabnzbdplus-0.7.3
===>  Applying FreeBSD patches for sabnzbdplus-0.7.3
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/bin/python2.7 - found
===>   sabnzbdplus-0.7.3 depends on shared library: intl - found
===>  Configuring for sabnzbdplus-0.7.3
===>  Installing for sabnzbdplus-0.7.3
===>   sabnzbdplus-0.7.3 depends on executable: cheetah - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/pythonutils/configobj.py - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/_sqlite3.so - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/bin/python2.7 - found
===>   sabnzbdplus-0.7.3 depends on executable: par2repair - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/OpenSSL/SSL.so - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/_yenc.so - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/feedparser.py - found
===>   sabnzbdplus-0.7.3 depends on executable: unrar - found
===>   Generating temporary packing list
===>  Checking if news/sabnzbdplus already installed
===> Creating users and/or groups.
Using existing group `_sabnzbd'.
Using existing user`_sabnzbd'.
install  -o root -g wheel -m 555 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/SABnzbd.py /usr/local/bin
install -d /usr/local/lib/python2.7/site-packages/sabnzbd
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/sabnzbd && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/lib/python2.7/site-packages/sabnzbd
install -d /usr/local/share/sabnzbdplus
/bin/mkdir -p /usr/local/share/sabnzbdplus/cherrypy
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/cherrypy && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/cherrypy
/bin/mkdir -p /usr/local/share/sabnzbdplus/gntp
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/gntp && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/gntp
/bin/mkdir -p /usr/local/share/sabnzbdplus/interfaces
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/interfaces && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/interfaces
/bin/mkdir -p /usr/local/share/sabnzbdplus/locale
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/locale && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/locale
/bin/mkdir -p /usr/local/share/sabnzbdplus/po
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/po && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/po
/bin/mkdir -p /usr/local/share/sabnzbdplus/tools
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/tools && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/tools
/bin/mkdir -p /usr/local/share/sabnzbdplus/util
cd /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/util && /bin/sh -c '(/usr/bin/find -d $0 $2 | /usr/bin/cpio -dumpl $1 >/dev/null  2>&1) &&  /usr/sbin/chown -R root:wheel $1 &&  /usr/bin/find -d $0 $2 -type d -exec chmod 755 $1/{} \; &&  /usr/bin/find -d $0 $2 -type f -exec chmod 444 $1/{} \;' -- * /usr/local/share/sabnzbdplus/util
===> Installing rc.d startup script(s)
/bin/mkdir -p /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/ABOUT.txt /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/CHANGELOG.txt /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/COPYRIGHT.txt /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/INSTALL.txt /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/ISSUES.txt /usr/local/share/doc/sabnzbdplus
install  -o root -g wheel -m 444 /usr/ports/news/sabnzbdplus/work/SABnzbd-0.7.3/README.txt /usr/local/share/doc/sabnzbdplus
/bin/mkdir -p /usr/local/sabnzbd
/usr/sbin/chown _sabnzbd:_sabnzbd /usr/local/sabnzbd

---

news/sabnzbdplus includes an RC script:
/usr/local/etc/rc.d/sabnzbd

TO START SABNZBD ON BOOT:
echo 'sabnzbd_enable="YES"' >> /etc/rc.conf

START MANUALLY:
/usr/local/etc/rc.d/sabnzbd start

Once started, visit the following to configure:
http://localhost:8080/sabnzbd/

Note that your URL may differ slightly if you have an old sabnzbd.ini
that specifies a different address to bind to.

---

===> Correct pkg-plist sequence to create group(s) and user(s)
===>   Registering installation for sabnzbdplus-0.7.3
===>  Cleaning for sabnzbdplus-0.7.3
sabnzbd                                       100% of 3650  B   25 MBps
sudo: unable to execute /usr/local/etc/rc.d/sabnzbd: No such file or directory

Failed! Installing Sabnzbd didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

Says failed, but it seems to be working fine tho.

**Comment by ghost** [comment]
I have to create a VM with ZFSguru beta7 and test some stuff. This will take a while.

**Comment by kxy1983s** [comment]
Appreciate the effort, In the meantime, I think im gonna roll back to the
last known working version.

**Comment by ghost** [comment]
I tested the installation of SAB, SB, CP and HP. everything installs and runs fine on ZFSguru system image 9.1-003
Can you confirm this?
