### ISSUE TITLE
Cannot run CouchPotato and Sickbeard both together

### ISSUE THREAD

**Issue by acortina-git** [Mar2zz/LaSi#46]
Hi all,

the issue that I'm having is similar to:

https://github.com/Mar2zz/LaSi/issues/31

If I try to launch couchpotato when sickbeard is already running i get:

[root@fs1 /usr/local/etc/rc.d]# ./couchpotato start
couchpotato already running? (pid=2752).
[root@fs1 /usr/local/etc/rc.d]# ps ax 
...
2752 ??  Is      0:00.00 daemon: python[2753](daemon)
2753 ??  S       0:06.23 python /usr/local/sickbeard/SickBeard.py --quiet --nolaunch
...

and like in issue #31 if I launch it by:

[root@fs1 /usr/local/etc/rc.d]# sudo -u share /usr/sbin/daemon -f -p /usr/local/couchpotato/couchpotato.pid python /usr/local/couchpotato/CouchPotato.py --quiet

then everything works :(

I've installed through LaSi:

Maraschino
CouchPotato
Sickbeard
SABnzbd
Transmission

I'm running LaSi in a clean install ZFSGuru 0.2-beta7 which is based on FreeBSD 9.1-RC1

Cheers,

**Comment by Elroban** [comment]
Alejojo,

This can be resolved by setting the pidfile. This can be done by adding the following lines to the corresponding startup files:
couchpotato, line 37: >> pidfile="${couchpotato_dir}/couchpotato.pid"
sickbeard, line 36: >> pidfile="${sickbeard_dir}/sickbeard.pid"
headphones, line 36: >> pidfile="${headphones_dir}/headphones.pid"

Changed it in #48

Hope this helps

**Comment by acortina-git** [comment]
Elroban, just tried, perfect! :DD
