### ISSUE TITLE
fout tijdens php /var/www/spotweb/upgrade-db.php

### ISSUE THREAD

**Issue by jteeuw** [Mar2zz/LaSi#5]
Ik krijg de wanneer ik php /var/www/spotweb/upgrade-db.php uit voer :

PHP Warning:  require_once(lib/SpotSecurity.php): failed to open stream: No such file or directory in /var/www/spotweb/lib/SpotClassAutoload.php on line 17
PHP Fatal error:  require_once(): Failed opening required 'lib/SpotSecurity.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/spotweb/lib/SpotClassAutoload.php on line 17

Ben ik iets vergeten te installeren  ( Ubuntu Linux 11.04 )

gr,
Jeroen

**Comment by Mar2zz** [comment]
Nee je bent niets vergeten, lijkt me niet, je hebt het script gebruikt neem ik aan dus je hebt gewoon de volledige gitversie. Die is nogal aan wijzigingen onderhevig dus vaak is iets 'even' stuk en dan weer goed. 

Probeer eens op te lossen met een pull (in terminal: cd /var/www/spotweb && git pull && php upgrade-db.php)

**Comment by jteeuw** [comment]
Dank voor de reactie, cd /var/www/spotweb && git pull && php upgrade-db.php werkt!
