### ISSUE TITLE
Sabnzbd on ZFSguru 0.2.0 beta8

### ISSUE THREAD

**Issue by webbier** [Mar2zz/LaSi#50]
Installing Sickbeard and Couchpotato works fine on ZFSguru 0.2.0-beta8, but installing Sabnzbd gives me some troubles:

Options:
1. Install Sabnzbd
2. Uninstall Sabnzbd

B. Back to menu
Q. Quit
1

Are you sure you want to continue and install Sabnzbd?

Ports Tree is up to date
===>  Installing for sabnzbdplus-0.7.3
===>   sabnzbdplus-0.7.3 depends on executable: cheetah - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages                    /pythonutils/configobj.py - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages                    /_sqlite3.so - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/bin/python2.7 - found
===>   sabnzbdplus-0.7.3 depends on executable: par2repair - not found
===>    Verifying install for par2repair in /usr/ports/archivers/par2cmdline-tbb
===>   par2cmdline-tbb-20100203_6 depends on file: /usr/local/bin/automake-1.12                     - found
===>   par2cmdline-tbb-20100203_6 depends on file: /usr/local/bin/autoconf-2.69                     - found
===>   par2cmdline-tbb-20100203_6 depends on shared library: tbb - not found
===>    Verifying install for tbb in /usr/ports/devel/tbb
===>  License GPLv2 accepted by the user
===>  Extracting for tbb-4.0.0
=> SHA256 Checksum mismatch for tbb40_233oss_src.tgz.
===>  Refetch for 1 more times files: tbb40_233oss_src.tgz
===>  License GPLv2 accepted by the user
=> tbb40_233oss_src.tgz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb                    40_233oss_src.tgz
fetch: http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb40_233oss_src.tg                    z: size unknown
fetch: http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb40_233oss_src.tg                    z: size of remote file is not known
tbb40_233oss_src.tgz                                    53 kB   92 kBps
===>  License GPLv2 accepted by the user
=> SHA256 Checksum mismatch for tbb40_233oss_src.tgz.
===>  Giving up on fetching files: tbb40_233oss_src.tgz
Make sure the Makefile and distinfo file (/usr/ports/devel/tbb/distinfo)
are up to date.  If you are absolutely sure you want to override this
check, type "make NO_CHECKSUM=yes [other args]".
**\* [checksum] Error code 1

Stop in /usr/ports/devel/tbb.
**\* [checksum] Error code 1

Stop in /usr/ports/devel/tbb.
**\* [lib-depends] Error code 1

Stop in /usr/ports/archivers/par2cmdline-tbb.
**\* [run-depends] Error code 1

Stop in /usr/ports/news/sabnzbdplus.

Failed! Installing Sabnzbd didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

Press a key to continue

**Comment by ghost** [comment]
Could you try running LaSi again?

I've performed a minor fix. Now the portstree will alwas update.

**Comment by webbier** [comment]
Unfortunately that did not solve the problem. After updating the ports tree I get the same message as before:

Options:
1. Install Sabnzbd
2. Uninstall Sabnzbd

B. Back to menu
Q. Quit
1

Are you sure you want to continue and install Sabnzbd?

Going to update the Ports Tree

Looking up portsnap.FreeBSD.org mirrors... none found.
Fetching public key from portsnap.FreeBSD.org... done.
Fetching snapshot tag from portsnap.FreeBSD.org... done.
Fetching snapshot metadata... done.
Fetching snapshot generated at Sun Nov 25 00:01:38 UTC 2012:
7090ea655d8f231658f526087a23ec9102ac0317b099dd100% of   68 MB  189 kBps 00m00s
Extracting snapshot... done.
Verifying snapshot integrity... done.
Fetching snapshot tag from portsnap.FreeBSD.org... done.
Fetching snapshot metadata... done.
Updating from Sun Nov 25 00:01:38 UTC 2012 to Sun Nov 25 09:07:39 UTC 2012.
Fetching 4 metadata patches... done.
Applying metadata patches... done.
Fetching 0 metadata files... done.
Fetching 6 patches.... done.
Applying patches... done.
Fetching 3 new ports or files... done.
/usr/ports was not created by portsnap.
You must run 'portsnap extract' before running 'portsnap update'.
===>  Installing for sabnzbdplus-0.7.3
===>   sabnzbdplus-0.7.3 depends on executable: cheetah - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/pythonutils/configobj.py - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/lib/python2.7/site-packages/_sqlite3.so - found
===>   sabnzbdplus-0.7.3 depends on file: /usr/local/bin/python2.7 - found
===>   sabnzbdplus-0.7.3 depends on executable: par2repair - not found
===>    Verifying install for par2repair in /usr/ports/archivers/par2cmdline-tbb
===>   par2cmdline-tbb-20100203_6 depends on file: /usr/local/bin/automake-1.12 - found
===>   par2cmdline-tbb-20100203_6 depends on file: /usr/local/bin/autoconf-2.69 - found
===>   par2cmdline-tbb-20100203_6 depends on shared library: tbb - not found
===>    Verifying install for tbb in /usr/ports/devel/tbb
===>  License GPLv2 accepted by the user
===>  Extracting for tbb-4.0.0
=> SHA256 Checksum mismatch for tbb40_233oss_src.tgz.
===>  Refetch for 1 more times files: tbb40_233oss_src.tgz
===>  License GPLv2 accepted by the user
=> tbb40_233oss_src.tgz doesn't seem to exist in /usr/ports/distfiles/.
=> Attempting to fetch http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb40_233oss_src.tgz
fetch: http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb40_233oss_src.tgz: size unknown
fetch: http://threadingbuildingblocks.org/uploads/78/174/4.0/tbb40_233oss_src.tgz: size of remote file is not known
tbb40_233oss_src.tgz                                    53 kB   23 kBps
===>  License GPLv2 accepted by the user
=> SHA256 Checksum mismatch for tbb40_233oss_src.tgz.
===>  Giving up on fetching files: tbb40_233oss_src.tgz
Make sure the Makefile and distinfo file (/usr/ports/devel/tbb/distinfo)
are up to date.  If you are absolutely sure you want to override this
check, type "make NO_CHECKSUM=yes [other args]".
**\* [checksum] Error code 1

Stop in /usr/ports/devel/tbb.
**\* [checksum] Error code 1

Stop in /usr/ports/devel/tbb.
**\* [lib-depends] Error code 1

Stop in /usr/ports/archivers/par2cmdline-tbb.
**\* [run-depends] Error code 1

Stop in /usr/ports/news/sabnzbdplus.

Failed! Installing Sabnzbd didn't finish, try again or:
Copy the text above and report an issue at the following address:
https://github.com/Mar2zz/LaSi/issues

Press a key to continue

**Comment by ghost** [comment]
Looks like you don't have a portstree present or did you install the portstree service provided by zfsguru?

 Try this command: portsnap fetch extract
