### ISSUE TITLE
errors when running manualAlbum.sh

### ISSUE THREAD

**Issue by mpetre** [Mar2zz/LaSi#6]
Ubuntu 10.4 here with all the updates installed.
I used the manualAlbum.sh before and worked fine.
The directory that I try to arrange has only one album in it running this :
/home/mishou/.albumidentify/manualAlbum.sh /media/Volume0/MP3/Madonna/ -R

Wed Jun 15 12:47:45 2011: ----renamealbum started----
Wed Jun 15 12:47:45 2011: ----renamealbum started----
Wed Jun 15 12:47:45 2011: Using naming scheme: %(albumartist)s/%(year)i - %(album)s/%(tracknumber)02i - %(trackname)s
Wed Jun 15 12:47:45 2011: Using dest prefix: /home/mishou/Music
Wed Jun 15 12:47:45 2011: Source path: /media/Volume0/MP3/Madonna/Ray Of Light
Wed Jun 15 12:47:45 2011: no dest enabled: lower quality destination files will be replaced
Wed Jun 15 12:47:45 2011: Skipping calculating discID
Wed Jun 15 12:47:45 2011: Trying to look up release via already tagged release-id
Wed Jun 15 12:47:45 2011: Trying fingerprint search
Wed Jun 15 12:47:47 2011: Traceback (most recent call last):
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/renamealbum", line 362, in process_one_path
    renamealbum(srcpath, options)
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/renamealbum", line 698, in renamealbum
    (release, method) = get_musicbrainz_release (disc, options)
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/renamealbum", line 274, in get_musicbrainz_release
    return (get_release_by_fingerprints(disc), "fingerprint")
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/renamealbum", line 97, in get_release_by_fingerprints
    dirinfo = albumidentify.get_dir_info(disc.dirname)
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/src/renamealbum/albumidentify.py", line 62, in get_dir_info
    for mbtrack in trackinfo[fname].getTracks():
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/src/renamealbum/musicfile.py", line 100, in getTracks
    self.tracks = lookups.get_tracks_by_puid(self.getPUID())
Wed Jun 15 12:47:47 2011: File "/home/mishou/.albumidentify/src/renamealbum/memocache.py", line 71, in memoify_replacement
    memocache[func.**name**][dbkey]=ret
Wed Jun 15 12:47:47 2011: File "/usr/lib/python2.6/shelve.py", line 133, in **setitem**
    self.dict[key] = f.getvalue()
Wed Jun 15 12:47:47 2011: File "/usr/lib/python2.6/bsddb/**init**.py", line 276, in **setitem**
    _DeadlockWrap(wrapF)  # self.db[key] = value
Wed Jun 15 12:47:47 2011: File "/usr/lib/python2.6/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(__args, *__kwargs)
Wed Jun 15 12:47:47 2011: File "/usr/lib/python2.6/bsddb/__init__.py", line 275, in wrapF
    self.db[key] = value
Wed Jun 15 12:47:47 2011: DBRunRecoveryError: (-30974, 'DB_RUNRECOVERY: Fatal error, run database recovery -- PANIC: Invalid argument')
Wed Jun 15 12:47:47 2011: fail!

**Comment by Mar2zz** [comment]
Could you post this issue here: https://github.com/scottr/albumidentify

I believe this isn't an issue from the manualScan.sh script, that runs the same command as you would do manually for renamealbum itself.
