### ISSUE TITLE
Periscope install scripts error

### ISSUE THREAD

**Issue by Hertog** [Mar2zz/LaSi#7]
Hi, I've just installed Periscope with your LaSi.sh script, and when I try to manually run it python is giving me this kind of errors :

OSError: [Errno 2] No such file or directory: 'INSTALLDIR/cache'
INFO:periscope:Creating folder INSTALLDIR/cache
Traceback (most recent call last):
  File "/home/download-user/periscope/downloadSub.py", line 13, in <module>
    subdl = periscope.Periscope(cache_folder="INSTALLDIR/cache")
  File "/home/download-user/periscope/periscope.py", line 56, in **init**
    os.mkdir(folder)
OSError: [Errno 2] No such file or directory: 'INSTALLDIR/cache'
INFO:periscope:Creating folder INSTALLDIR/cache
Traceback (most recent call last):
  File "/home/download-user/periscope/downloadSub.py", line 13, in <module>
    subdl = periscope.Periscope(cache_folder="INSTALLDIR/cache")
  File "/home/download-user/periscope/periscope.py", line 56, in **init**
    os.mkdir(folder)
OSError: [Errno 2] No such file or directory: 'INSTALLDIR/cache'

To me it seems like an error in your lasi/periscopeinstall.sh, cuz INSTALLDIR is a variable from your lasi/periscopeinstall.sh and after I edited downloadSub.py and changed INSTALLDIR to my installation directory, it worked! 

BTW; This is on a Debian stable (squeeze) machine

**Comment by Mar2zz** [comment]
You are right, did you use the dropbox installfile or this one on github?
in dropbox I allready added: mkdir -p $INSTALLDIR/cache to the installation and edited downloadSub.py like this sed -i "s/INSTALLDIR/$INSTALLDIR/g" $INSTALLDIR/$DOWN_SUB, on github not yet

I should sync the other way around github to dropbox instead of dropbox to github :p

**Comment by Hertog** [comment]
I downloaded the "master" install script (if i can call it that way) from github, and then that script downloaded another script from dropbox.

**Comment by Mar2zz** [comment]
Allright. Thx for reporting. I fixed it. sed tripped over the use of / because I was editing paths. Using # now instead of / and confirmed it worked. I still need to update github with it, but the dropbox file is up2date now :)
