### ISSUE TITLE
Albumidentify synology

### ISSUE THREAD

**Issue by robderijk** [Mar2zz/LaSi#9]
Like the title says, it would be nice if albumidentify is included in the synology lasi script! I would love to have it on my nas.

**Comment by Mar2zz** [comment]
I need to know what ipkg's packagelist is. (i don't have a synology, so I can't check). I can write such a script, but I need to know what the names are for all dependency's. Can you help finding the correct names?

These are dependency's on Ubuntu I don't know if ipkg has those too:
PACK3="python-musicbrainz2 python-imaging";
PACK4="libsndfile1 sndfile-programs libofa0";

Optional, depending on what you want to rename:
for mp3
PACK5=mpg123
PACK6=mp3gain
for flac
PACK7=flac
for ogg.
PACK9=vorbisgain
PACK8=vorbis-tools

for ripping cd's:
cdrdao cueconvert bchunk flac

**Comment by robderijk** [comment]
Hi,

thanks for your reply!

I checked the ipkg list and only these dependency's are available:

libsndfile
mpg123
flac
vorbis-tools

So that's not much. I tried compiling the required dependency's from source but I'm stuck with the libofa0 library. Albumidentify keeps telling me "Fingerprinting support not installed, please install libofa0". I used the 0.9.3 version at http://code.google.com/p/musicip-libofa/downloads/list and succesfully compiled and installed it but the error remains. Any ideas?

**Comment by Mar2zz** [comment]
I think the python musicbrainz is needed too. Maybe it would be easier to use beets on syno? (thats what headphones uses too) http://beets.readthedocs.org/en/latest/guides/main.html

I'll do some tests on ubuntu, to see if beets can do what albumidentify can.

**Comment by Mar2zz** [comment]
Well, back on Beets now. It's a great program, and I think it can run on a synology too. If someone can try to install it and succeeds, give me the code and I will script it.
think install on syno is something like this:

ipkg install git
ipkg install python26
ipkg install py26-setuptools
easy_install pip
- if it errors: is not on sys.path, install pip with the following:
  curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python
  /opt/local/bin/pip install beets
- config needs to be set in /home/user/.beetsconfig (does syno have home-directory's?)
- info about configfile: http://beets.readthedocs.org/en/latest/reference/config.html
  /opt/local/bin/beet import /path/to/new/music
  /opt/local/bin/beet help for more options

**Comment by robderijk** [comment]
This works for me! I followed your steps and easy_install pip failed but curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python
/opt/local/bin/pip install beets
succeeded. Synology does have home directories, however it needs to be turned on in the syno manager. Location to turn it on: Control Panel -> User -> User Home.

**Comment by Mar2zz** [comment]
Great.
I need to know 2 things:
where is beets executable located? which beet
Did you process an album? Could you try one with /opt/local/bin/pip beet -q "/path/to/album"

**Comment by Mar2zz** [comment]
Maybe easy_install pip needs to be changed to /opt/local/bin/easy_install pip (or whatever the path is from easy_install).

**Comment by Mar2zz** [comment]
Updated the syn_installer with Beets, but also rewritten the complete install script. Can have a lot of bugs now (it won't mess up your syno, on every error it finds it will exit the script and asks to post an issue here.)

The old installer will not work anymore because I deleted all old installscripts from dropbox. 

feel free to try and report back :)

**Comment by Mar2zz** [comment]
Beets seems to work (I heard from others on Tweakers.net), so I am closing this issue.
